/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PocketPokerEscrowCUSD {
  export type MatchViewStruct = {
    playerA: AddressLike;
    playerB: AddressLike;
    stake: BigNumberish;
    playerAFunded: boolean;
    playerBFunded: boolean;
    playerAReady: boolean;
    playerBReady: boolean;
    resolved: boolean;
    winner: AddressLike;
  };

  export type MatchViewStructOutput = [
    playerA: string,
    playerB: string,
    stake: bigint,
    playerAFunded: boolean,
    playerBFunded: boolean,
    playerAReady: boolean,
    playerBReady: boolean,
    resolved: boolean,
    winner: string
  ] & {
    playerA: string;
    playerB: string;
    stake: bigint;
    playerAFunded: boolean;
    playerBFunded: boolean;
    playerAReady: boolean;
    playerBReady: boolean;
    resolved: boolean;
    winner: string;
  };
}

export interface PocketPokerEscrowCUSDInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cUSDTokenAddress"
      | "fundStake"
      | "getMatch"
      | "markReady"
      | "owner"
      | "payoutWinner"
      | "potAmount"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchResolved"
      | "OwnershipTransferred"
      | "PlayerReady"
      | "StakeFunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cUSDTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundStake",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getMatch", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "markReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutWinner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "potAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cUSDTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markReady", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "potAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MatchResolvedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    winner: AddressLike,
    payout: BigNumberish
  ];
  export type OutputTuple = [matchId: string, winner: string, payout: bigint];
  export interface OutputObject {
    matchId: string;
    winner: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerReadyEvent {
  export type InputTuple = [matchId: BytesLike, player: AddressLike];
  export type OutputTuple = [matchId: string, player: string];
  export interface OutputObject {
    matchId: string;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeFundedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [matchId: string, player: string, amount: bigint];
  export interface OutputObject {
    matchId: string;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PocketPokerEscrowCUSD extends BaseContract {
  connect(runner?: ContractRunner | null): PocketPokerEscrowCUSD;
  waitForDeployment(): Promise<this>;

  interface: PocketPokerEscrowCUSDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cUSDTokenAddress: TypedContractMethod<[], [string], "view">;

  fundStake: TypedContractMethod<
    [matchId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getMatch: TypedContractMethod<
    [matchId: BytesLike],
    [PocketPokerEscrowCUSD.MatchViewStructOutput],
    "view"
  >;

  markReady: TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  payoutWinner: TypedContractMethod<
    [matchId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  potAmount: TypedContractMethod<[matchId: BytesLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cUSDTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundStake"
  ): TypedContractMethod<
    [matchId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BytesLike],
    [PocketPokerEscrowCUSD.MatchViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markReady"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutWinner"
  ): TypedContractMethod<
    [matchId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "potAmount"
  ): TypedContractMethod<[matchId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MatchResolved"
  ): TypedContractEvent<
    MatchResolvedEvent.InputTuple,
    MatchResolvedEvent.OutputTuple,
    MatchResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlayerReady"
  ): TypedContractEvent<
    PlayerReadyEvent.InputTuple,
    PlayerReadyEvent.OutputTuple,
    PlayerReadyEvent.OutputObject
  >;
  getEvent(
    key: "StakeFunded"
  ): TypedContractEvent<
    StakeFundedEvent.InputTuple,
    StakeFundedEvent.OutputTuple,
    StakeFundedEvent.OutputObject
  >;

  filters: {
    "MatchResolved(bytes32,address,uint256)": TypedContractEvent<
      MatchResolvedEvent.InputTuple,
      MatchResolvedEvent.OutputTuple,
      MatchResolvedEvent.OutputObject
    >;
    MatchResolved: TypedContractEvent<
      MatchResolvedEvent.InputTuple,
      MatchResolvedEvent.OutputTuple,
      MatchResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlayerReady(bytes32,address)": TypedContractEvent<
      PlayerReadyEvent.InputTuple,
      PlayerReadyEvent.OutputTuple,
      PlayerReadyEvent.OutputObject
    >;
    PlayerReady: TypedContractEvent<
      PlayerReadyEvent.InputTuple,
      PlayerReadyEvent.OutputTuple,
      PlayerReadyEvent.OutputObject
    >;

    "StakeFunded(bytes32,address,uint256)": TypedContractEvent<
      StakeFundedEvent.InputTuple,
      StakeFundedEvent.OutputTuple,
      StakeFundedEvent.OutputObject
    >;
    StakeFunded: TypedContractEvent<
      StakeFundedEvent.InputTuple,
      StakeFundedEvent.OutputTuple,
      StakeFundedEvent.OutputObject
    >;
  };
}
